updated postinst

diff --git a/debian/signal-sidecar.postinst b/debian/signal-sidecar.postinst
--- a/debian/signal-sidecar.postinst
+++ b/debian/signal-sidecar.postinst
@@ -1,40 +1,55 @@
 #!/bin/bash
+# postinst script for jitsi-meet
+#
+# see: dh_installdeb(1)
 
-die () {
-    echo >&2 "$@"
-    exit 1
-}
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 case "$1" in
     configure)
+        CONFIG="/etc/jitsi/signal-sidecar/config"
 
+        # we don't want to start the daemon as root
         if ! getent group jitsi > /dev/null ; then
             groupadd jitsi
         fi
-
-        if ! getent passwd jibri > /dev/null ; then
-            echo "Creating jibri user and group"
-            # Create the Jibri user and group
-            useradd --system --create-home jibri
-            echo "Done creating jibri user and group"
-            usermod -a -G jibri,jitsi,audio,video jibri
-            echo "jibri user added to audio, video and jibri groups"
+        if ! getent passwd signal-sidecar > /dev/null ; then
+            useradd -r -g jitsi --shell /bin/bash --create-home -d /usr/share/signal-sidecar signal-sidecar
+        fi
+        if ! groups signal-sidecar | grep '\bjitsi\b' > /dev/null ; then
+            usermod -g jitsi signal-sidecar
         fi
 
-        # Make the directory for the logs and set the permissions
-        mkdir -p /var/log/jitsi/jibri
-        chgrp jitsi /var/log/jitsi/jibri
-        chmod g+w /var/log/jitsi/jibri
-
-        # Move the asoundrc file to the jibri home directory
-        if [ -f /etc/jitsi/jibri/asoundrc ] ; then
-            mv /etc/jitsi/jibri/asoundrc /home/jibri/.asoundrc
+        # we create home folder only if it doesn't exist
+        if [ ! -d /usr/share/signal-sidecar ]; then
+            mkdir -p /usr/share/signal-sidecar
         fi
 
-        # Make the directory for the icewm preferences and move the preferences file into it
-        if [ -f /etc/jitsi/jibri/icewm.preferences ] ; then
-            mkdir -p /home/jibri/.icewm
-            mv /etc/jitsi/jibri/icewm.preferences /home/jibri/.icewm/preferences
+        # we claim the home folder of signal-sidecar in case it is owned by someone else
+        OWNER=$(stat -c '%U' /usr/share/signal-sidecar)
+        GROUP=$(stat -c '%G' /usr/share/signal-sidecar)
+        if ! dpkg-statoverride --list /usr/share/signal-sidecar/* >/dev/null && [ "$OWNER:$GROUP" != "signal-sidecar:jitsi" ]; then
+            chown -R signal-sidecar:jitsi /usr/share/signal-sidecar
+            OWNER=signal-sidecar
+            GROUP=jitsi
+        fi
+
+        CONFIG_DIR=$(dirname $CONFIG)
+        if ! dpkg-statoverride --list "$CONFIG_DIR" >/dev/null; then
+                chown root:$GROUP "$CONFIG_DIR"
+                chmod 750 "$CONFIG_DIR"
         fi
     ;;
 
@@ -47,4 +62,10 @@ case "$1" in
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
 exit 0
+
